

#define FZ1_POWER

#define SERVO_STEP_SIZE_ANGLE 1
#define SERVO_STEP_DELAY_MS 30
#define SERVO_CMD_TIMEOUT_MS 5000

#define SPEAKER1_VOLUME 3  // range 0-30

#define SIGNAL_SLOW_BLINK_FREQ 1000
#define SIGNAL_FAST_BLINK_FREQ 600
